version: '3'

services:
    bot:
        build:
            dockerfile: Dockerfile
            args:
                DATABASE_URL: mysql://root:root@localhost:3306/distro_deploy
        networks:
            - bot
        environment:
            DATABASE_URL: mysql://root:root@localhost:3306/distro_deploy
        depends_on:
            - database

    database:
        image: mariadb:lts
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: distro_deploy
        volumes:
            - distro_deploy_database:/var/lib/mysql
        networks:
            - bot

volumes:
    distro_deploy_database:

networks:
    bot:
