version: '3'

# Development
services:
    database:
        image: mariadb:lts
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: distro_deploy
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        volumes:
            - data:/var/lib/mysql
        ports:
            - '3306:3306'

volumes:
    data:
