version: '3'

services:
    bot:
        build: .
        networks:
            - bot
        environment:
            DATABASE_URL: mysql://root:root@localhost:3306/distro_deploy
    database:
        image: mariadb:lts
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: distro_deploy
        volumes:
            - distro_deploy_database:/var/lib/mysql
        networks:
            - bot

volumes:
    data:

networks:
    bot:
