version: '3'

services:
    bot:
        build: .
        networks:
            - bot
        environment:
            DATABASE_URL: mysql://root:root@database:3306/distro_deploy
        depends_on:
            database:
                condition: service_healthy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    database:
        image: mariadb:lts
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: distro_deploy
        volumes:
            - distro_deploy_database:/var/lib/mysql
        healthcheck:
            test:
                [
                    'CMD',
                    '/usr/local/bin/healthcheck.sh',
                    '--su-mysql',
                    '--connect',
                    '--innodb_initialized',
                ]
        networks:
            - bot

volumes:
    distro_deploy_database:

networks:
    bot:
