version: '3'

services:
    bot:
        build: .
        networks:
            - bot
        environment:
            DATABASE_URL: mysql://root:root@database:3306/distro_deploy?connect_timeout=15
        depends_on:
            - database
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    database:
        image: mariadb:lts
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: distro_deploy
        volumes:
            - distro_deploy_database:/var/lib/mysql
        networks:
            - bot

volumes:
    distro_deploy_database:

networks:
    bot:
